name: "И Feedback de Funciones Experimentales"
description: "Reporta tu experiencia probando los Feature Flags de desarrollo"
title: "[LAB] <Funci贸n probada - Feedback>"
labels: ["experimental", "feedback"]
body:
  - type: markdown
    attributes:
      value: |
        隆Gracias por ser un Early Adopter! Tu feedback nos ayuda a mover estas funciones a la rama estable.
  - type: dropdown
    id: feature
    attributes:
      label: "驴Qu茅 caracter铆stica estabas probando?"
      options:
        - "Selector de Color (dragonruby-enable-picker)"
        - "Smart Jump (dragonruby-experimental-smart-jump)"
        - "Living Documentation (dragonruby-experimental-concepts-docs)"
        - "Otro / Varios"
    validations:
      required: true
  - type: textarea
    id: experience
    attributes:
      label: "驴C贸mo fue tu experiencia?"
      description: "驴Funcion贸 como esperabas? 驴Qu茅 te gustar铆a cambiar?"
    validations:
      required: true
  - type: textarea
    id: bug-dev
    attributes:
      label: "驴Encontraste alg煤n error t茅cnico?"
      description: "Si algo fall贸 o tir贸 error, pega el mensaje aqu铆."
  - type: textarea
    id: ideas
    attributes:
      label: "Sugerencias para esta funci贸n"
      description: "驴C贸mo podr铆amos hacer que esta funci贸n sea 'imprescindible'?"
