name: "🧪 Experimental Features Feedback"
description: "Report your experience testing development Feature Flags"
title: "[LAB] <Tested feature - Feedback>"
labels: ["experimental", "feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for being an Early Adopter! Your feedback helps us move these features to the stable branch.
  - type: dropdown
    id: feature
    attributes:
      label: "Which feature were you testing?"
      options:
        - "Color Picker (dragonruby-enable-picker)"
        - "Smart Jump (dragonruby-experimental-smart-jump)"
        - "Living Documentation (dragonruby-experimental-concepts-docs)"
        - "Other / Multiple"
    validations:
      required: true
  - type: textarea
    id: experience
    attributes:
      label: "How was your experience?"
      description: "Did it work as expected? What would you like to change?"
    validations:
      required: true
  - type: textarea
    id: bug-dev
    attributes:
      label: "Did you find any technical errors?"
      description: "If something failed or threw an error, paste the message here."
  - type: textarea
    id: ideas
    attributes:
      label: "Suggestions for this feature"
      description: "How could we make this feature 'essential'?"

  - type: textarea
    id: visual-feedback
    attributes:
      label: "Visual Feedback (Images/Videos)"
      description: "If you want to show how a feature looks (or fails to look) in your setup, paste it here."
