name: "💡 Feature Request / Enhancement"
description: "Suggest an idea or improvement for DragonRuby Mode"
title: "[FEAT] <Enhancement summary>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for wanting to improve DragonRuby Mode! Describe your idea in as much detail as possible.
  - type: textarea
    id: problem
    attributes:
      label: "What problem does this enhancement solve?"
      description: "Explain why this feature is necessary."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you envision"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives considered"
      description: "Describe any alternative solutions or features you've considered."
  - type: textarea
    id: visual-reference
    attributes:
      label: "Visual Reference / Mockups"
      description: "Do you have a mockup or an example of how this should look? Paste it here!"
  - type: textarea
    id: context
    attributes:
      label: "Additional context"
      description: "Add any other information or code snippets that help understand the idea."
