;;; dragonruby-stargate-portal.el --- Stargate Portal Generator (Law XIX) -*- lexical-binding: t -*-

(require 'dragonruby-utils)

(defvar dragonruby-stargate--initialization-requested nil)
(defvar dragonruby-stargate--initialization-request-time nil)

(defun dragonruby-stargate-portal-create ()
  "Flatten and create the stargate_portal.rb for DragonRuby."
  (let* ((root (or (dragonruby--find-project-root t) dragonruby--last-detected-project-root))
         (mygame-dir (expand-file-name "mygame/" root))
         (portal-file (expand-file-name "stargate_portal.rb" mygame-dir))
         (runtime-dir (expand-file-name "modules/stargate/runtime" dragonruby-mode-root))
         (runtime-files '("random.rb" "chronos.rb" "black_box.rb" "state.rb" "protocol.rb" "injection.rb" "commands.rb" "timeline.rb" "clock.rb" "bootstrap.rb" "stargate_init.rb")))

    (unless (file-directory-p mygame-dir)
      (make-directory mygame-dir t))

    (with-temp-file portal-file
      (set-buffer-file-coding-system 'utf-8-unix)
      (insert "# Stargate Portal (Law XIX: Hot Reload Contract)\n")
      (insert "# This file is auto-generated by Emacs and contains the flattened Stargate Runtime.\n\n")
      (dolist (file runtime-files)
        (let ((start (point)))
          (insert (format "\n# --- SRC: %s ---\n" file))
          (insert-file-contents (expand-file-name file runtime-dir))
          (goto-char (point-max))
          (save-excursion
            (save-restriction
              (narrow-to-region start (point))
              (goto-char (point-min))
              ;; Clean up nested requires mid-concatenation
              (while (re-search-forward "^\\s-*require\\(_relative\\)?\\s-+['\"]\\(chronos\\|commands\\|timeline\\|protocol\\|state\\|random\\|injection\\|clock\\|bootstrap\\|stargate_init\\)['\"]" nil t)
                (replace-match "# [FLATTEN] \\&")))))))
    
    (setq dragonruby-stargate--initialization-requested t)
    (setq dragonruby-stargate--initialization-request-time (current-time))
    (message "📡 STARGATE: Portal created and anchored.")))

(provide 'dragonruby-stargate-portal)
